using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace Codecool.CodecoolShop
{
    public class EmailSender
    {
        public static async Task Execute()
        {//                                                 this key was generated by send grid, DO NOT TOUCH!!!
            //var apiKey = Environment.GetEnvironmentVariable("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");
            var apiKey = "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";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("alin10nastasa@gmail.com", "RunTime Terror");
            var subject = "Purchase confirmation from CodeCool Shop";
            var to = new EmailAddress("subtilebug.exe@gmail.com", "Example User");
            var plainTextContent = "and easy to do anywhere, even with python";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);

        }
    }
    /// i dont know in wich folder this should stay but its ok
    ///             EmailSender.Execute();
    /// copy this where you need to call the function, 
    /// the "var to" should take the mail from the form, or user DB when it will be ready
}
